//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int idproducto { get; set; }
        public string nombre { get; set; }
        public string precio { get; set; }
        public string detalles { get; set; }
        public string cantidad { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idusuarioCrea { get; set; }
        public Nullable<int> idusuarioModifica { get; set; }
        public Nullable<int> idtienda { get; set; }
    }
}
