//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoCuenta
    {
        public int idtipoCuenta { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> ididusuarioCrea { get; set; }
        public Nullable<int> idusuarioModifica { get; set; }
    }
}
