//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int idventa { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idusuarioCrea { get; set; }
        public Nullable<int> idusuarioModifica { get; set; }
        public Nullable<int> idtienda { get; set; }
    
        public virtual tienda tienda { get; set; }
    }
}
